os_images_auth:
  auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
  username: "{{ lookup('env','OS_USERNAME') }}"
  password: "{{ lookup('env','OS_PASSWORD') }}"
  project_name: "{{ lookup('env','OS_TENANT_NAME') }}"
  user_domain_name: "{{ lookup('env','OS_USER_DOMAIN_NAME') }}"
  project_domain_name: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') }}"
